### ISSUE TITLE
Setting SPARK_HOME in R Spark example

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-spark#49]
### Expected Behavior

-

### Actual Behaviour

In the R Spark flow example provided here: https://kestra.io/plugins/plugin-spark/tasks/io.kestra.plugin.spark.RSubmit
What should be SPARK_HOME set as in the env variable?

This runs in a Docker runner, so its unclear as to what should be set as SPARK_HOME. 
Once we know how the flow should exactly be, I can make changes in the documentation accordingly.

### Steps To Reproduce

N/A

### Environment Information

- Kestra Version: Any version
- Plugin version: Any version
- Operating System (OS / Docker / Kubernetes): N/A
- Java Version (If not docker): N/A

### Example flow

Flow as provided here: https://kestra.io/plugins/plugin-spark/tasks/io.kestra.plugin.spark.RSubmit

**Comment by anna-geller** [comment]
Sys.getenv("SPARK_HOME") should normally resolve to /opt/bitnami/spark if you're running this script with a default bitnami/spark image

**Comment by anna-geller** [comment]
the default example 

```yaml
id: "r_submit"
type: "io.kestra.plugin.spark.RSubmit"
runner: DOCKER
docker:
  networkMode: host
  user: root
master: spark://localhost:7077
mainScript: |
  library(SparkR, lib.loc = c(file.path(Sys.getenv("SPARK_HOME"), "R", "lib")))
  sparkR.session()
   
  print("The SparkR session has initialized successfully.")
   
  sparkR.stop()
```

from [here](https://kestra.io/plugins/tasks/io.kestra.plugin.spark.RSubmit) fails with error:
`Exception in thread "main" java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory`

![image](https://github.com/kestra-io/plugin-spark/assets/86264395/687851ed-eab9-4f25-b3a9-5d45ea11e81f)
